ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF6';
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

CREATE TABLE GRAD_SCHOOL
as
SELECT
    SYS_GUID() as GRAD_SCHOOL_ID,
    CAST(REPLACE(school.SCHOOL_ID,'-','') AS RAW(16)) as SCHOOL_ID,
    CASE
        WHEN (SELECT TRIM(APPEND_TRANS) FROM TAB_SCHOOL WHERE TRIM(MINCODE) = (SELECT dist.DISTRICT_NUMBER || school.SCHOOL_NUMBER from DISTRICT dist WHERE dist.DISTRICT_ID = school.DISTRICT_ID)) = 'Y' THEN 'REPLACE'
        ELSE 'APPEND'
        END as SUBMISSION_MODE_CODE,
    CASE
        WHEN school."can_issue_transcripts" = 'true' THEN 'Y'
        ELSE 'N'
        END as CAN_ISSUE_TRANSCRIPTS,
    CASE
        WHEN school."can_issue_certificates" = 'true' THEN 'Y'
        ELSE 'N'
        END as CAN_ISSUE_CERTIFICATES,
    'GRAD_SCHOOL_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'GRAD_SCHOOL_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL school;

CREATE TABLE GRAD_SCHOOL_HISTORY
as
SELECT
    SYS_GUID() as GRAD_SCHOOL_HISTORY_ID,
    gs.*
FROM GRAD_SCHOOL gs;



