CREATE TABLE GRAD_SCHOOL_SHEDLOCK
(
    NAME       VARCHAR(64),
    LOCK_UNTIL TIMESTAMP(3) NULL,
    LOCKED_AT  TIMESTAMP(3) NULL,
    LOCKED_BY  VARCHAR(255),
    CONSTRAINT GRAD_SCHOOL_SHEDLOCK_PK PRIMARY KEY (NAME)
);
