ALTER TABLE GRAD_SCHOOL MODIFY CREATE_USER VARCHAR2(100);
ALTER TABLE GRAD_SCHOOL MODIFY UPDATE_USER VARCHAR2(100);
ALTER TABLE GRAD_SCHOOL_HISTORY MODIFY CREATE_USER VARCHAR2(100);
ALTER TABLE GRAD_SCHOOL_HISTORY MODIFY UPDATE_USER VARCHAR2(100);
