CREATE TABLE GRAD_SCHOOL_EVENT
(
    EVENT_ID      RAW(16)                                NOT NULL,
    EVENT_STATUS  VARCHAR2(50)                           NOT NULL,
    EVENT_TYPE    VARCHAR2(100)                          NOT NULL,
    EVENT_OUTCOME VARCHAR2(100)                          NOT NULL,
    REPLY_CHANNEL VARCHAR2(100),
    CREATE_USER   VARCHAR2(100)                          NOT NULL,
    CREATE_DATE   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER   VARCHAR2(100)                          NOT NULL,
    UPDATE_DATE   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EVENT_PAYLOAD BLOB                                   NOT NULL,
    CONSTRAINT GRAD_SCHOOL_EVENT_PK PRIMARY KEY (EVENT_ID)
);

CREATE INDEX GRAD_SCHOOL_EVENT_EVENT_STATUS_IDX ON GRAD_SCHOOL_EVENT (EVENT_STATUS);
CREATE INDEX GRAD_SCHOOL_EVENT_EVENT_TYPE_IDX ON GRAD_SCHOOL_EVENT (EVENT_TYPE);
