CREATE TABLE GRAD_SCHOOL
(
    GRAD_SCHOOL_ID                      UUID NOT NULL,
    SCHOOL_ID                           UUID NOT NULL,
    SUBMISSION_MODE_CODE                VARCHAR(10) NOT NULL,
    CAN_ISSUE_TRANSCRIPTS               BOOLEAN NOT NULL,
    CAN_ISSUE_CERTIFICATES              BOOLEAN NOT NULL,
    CREATE_USER                         VARCHAR(32)         NOT NULL,
    CREATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                         VARCHAR(32)         NOT NULL,
    UPDATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT GRAD_SCHOOL_ID_PK PRIMARY KEY (GRAD_SCHOOL_ID)
);

CREATE TABLE GRAD_SCHOOL_HISTORY
(
    GRAD_SCHOOL_HISTORY_ID              UUID NOT NULL,
    GRAD_SCHOOL_ID                      UUID NOT NULL,
    SCHOOL_ID                           UUID NOT NULL,
    SUBMISSION_MODE                     VARCHAR(10) NOT NULL,
    TRANSCRIPT_ELIGIBILITY              BOOLEAN NOT NULL,
    CERTIFICATE_ELIGIBILITY             BOOLEAN NOT NULL,
    CREATE_USER                         VARCHAR(32)         NOT NULL,
    CREATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                         VARCHAR(32)         NOT NULL,
    UPDATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SCHOOL_HISTORY_ID_PK PRIMARY KEY (GRAD_SCHOOL_HISTORY_ID)
);

-------------------------------------------------CODE TABLES--------------------------------

CREATE TABLE SUBMISSION_MODE_CODE
(
    SUBMISSION_MODE_CODE              VARCHAR(10)           NOT NULL,
    LABEL                             VARCHAR(30) NOT NULL,
    DESCRIPTION                       VARCHAR(255) NOT NULL,
    DISPLAY_ORDER                     NUMERIC DEFAULT 1       NOT NULL,
    EFFECTIVE_DATE                    TIMESTAMP                   NOT NULL,
    EXPIRY_DATE                       TIMESTAMP                   NOT NULL,
    CREATE_USER                       VARCHAR(32)           NOT NULL,
    CREATE_DATE                       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                       VARCHAR(32)           NOT NULL,
    UPDATE_DATE                       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SUBMISSION_MODE_CODE_PK PRIMARY KEY (SUBMISSION_MODE_CODE)
);


--School & School History Foreign Keys
ALTER TABLE GRAD_SCHOOL
    ADD CONSTRAINT FK_GRAD_SCHOOL_SUBMISSION_MODE_CODE FOREIGN KEY (SUBMISSION_MODE_CODE) REFERENCES SUBMISSION_MODE_CODE (SUBMISSION_MODE_CODE),
    ADD CONSTRAINT GRAD_SCHOOL_SCHOOL_ID_UK UNIQUE (SCHOOL_ID);
ALTER TABLE GRAD_SCHOOL_HISTORY
    ADD CONSTRAINT FK_GRAD_SCHOOL_HISTORY_HISTORY_SCHOOL_ID FOREIGN KEY (GRAD_SCHOOL_ID) REFERENCES GRAD_SCHOOL (GRAD_SCHOOL_ID);

